name: coverity-scan
on:
  schedule:
    - cron: '0 18 * * *' # Daily at 18:00 UTC

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo sed /etc/apt/sources.list -e "s/^# deb-src/deb-src/g" -i
          sudo apt-get update
          sudo apt-get install ruby2.5
          sudo apt-get build-dep ruby2.5

      - name: Checkout ruby/ruby
        run: |
          git clone --depth=1 https://github.com/ruby/ruby .

      - name: Download Coverity Build Tool
        run: |
          wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=ruby" -O cov-analysis-linux64.tar.gz
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share

      - name: Run autoconf
        run: autoconf

      - name: Configure
        run: ./configure

      - name: Build with cov-build
        run: |
          export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int make

      - name: Submit the result to Coverity Scan
        run: |
          tar czvf ruby.tgz cov-int
          curl \
            --form project=ruby \
            --form token=$TOKEN \
            --form email=mame@ruby-lang.org \
            --form file=@ruby.tgz \
            --form version=trunk \
            --form description="`./ruby -v`" \
            https://scan.coverity.com/builds?project=ruby
        env:
          TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
